//! Detect auto-generated source files.

pub fn is_generated(content: &str) -> bool {
    let head = content.chars().take(2048).collect::<String>();
    let patterns = [
        "// Code generated",
        "// DO NOT EDIT",
        "# Code generated",
        "AUTO-GENERATED",
        "@generated",
        "//go:build ignore",
    ];
    patterns.iter().any(|p| head.contains(p)) || looks_minified(content)
}

const MINIFIED_SAMPLE_BYTES: usize = 64 * 1024;
const MINIFIED_MEAN_LINE_CHARS: usize = 500;

/// Bundler output packs a whole program into a few huge lines. Its one-letter names
/// would flood the graph with bogus inferred edges.
fn looks_minified(content: &str) -> bool {
    let mut end = content.len().min(MINIFIED_SAMPLE_BYTES);
    while !content.is_char_boundary(end) {
        end -= 1;
    }
    let sample = &content[..end];
    let lines = sample.lines().filter(|l| !l.trim().is_empty()).count().max(1);
    sample.len() / lines > MINIFIED_MEAN_LINE_CHARS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minified_bundle_is_generated() {
        let bundle = format!("\"use strict\";\n{}\n", "var a=function(b){return b+1},c=a(2);".repeat(400));
        assert!(is_generated(&bundle));
    }

    #[test]
    fn ordinary_source_with_one_long_line_is_not_generated() {
        let mut source = "function add(a, b) {\n  return a + b;\n}\n".repeat(200);
        source.push_str(&format!("const table = \"{}\";\n", "x".repeat(3_000)));
        assert!(!is_generated(&source));
    }

    #[test]
    fn marker_comment_is_still_generated() {
        assert!(is_generated("// Code generated by protoc. DO NOT EDIT.\npackage x\n"));
    }
}
