//! Architecture report rendering (graphify `GRAPH_REPORT.md` equivalent).

use std::collections::BTreeMap;
use std::fmt::Write as _;

use ax_graph::GraphInsights;
use ax_types::Node;

/// Inputs for rendering the architecture report.
pub struct ReportInput<'a> {
    pub project_name: &'a str,
    pub insights: &'a GraphInsights,
    pub dead_code: &'a [Node],
    pub unresolved_total: usize,
    /// (reference_name, count) for the most common unresolved references.
    pub unresolved_top: &'a [(String, usize)],
}

/// Render a full Markdown architecture report.
pub fn render_architecture_report(input: &ReportInput) -> String {
    let ins = input.insights;
    let mut out = String::new();

    let _ = writeln!(out, "# Architecture Report: {}", input.project_name);
    out.push('\n');
    let _ = writeln!(
        out,
        "Generated by `ax report`. This is a static snapshot of the code knowledge graph."
    );
    out.push('\n');

    // Overview
    let _ = writeln!(out, "## Overview\n");
    let _ = writeln!(out, "| Metric | Value |");
    let _ = writeln!(out, "| --- | ---: |");
    let _ = writeln!(out, "| Nodes | {} |", ins.node_count);
    let _ = writeln!(out, "| Edges | {} |", ins.edge_count);
    let _ = writeln!(out, "| Communities | {} |", ins.num_communities);
    let _ = writeln!(out, "| Modularity | {:.3} |", ins.modularity);
    let _ = writeln!(out, "| God nodes | {} |", ins.god_nodes.len());
    let _ = writeln!(out, "| Dead code candidates | {} |", input.dead_code.len());
    let _ = writeln!(out, "| Unresolved references | {} |", input.unresolved_total);
    out.push('\n');

    // God nodes
    let _ = writeln!(out, "## God Nodes\n");
    let _ = writeln!(
        out,
        "The most connected symbols — changes here have the widest blast radius.\n"
    );
    if ins.god_nodes.is_empty() {
        let _ = writeln!(out, "_None detected._\n");
    } else {
        let _ = writeln!(out, "| # | Symbol | Kind | Degree | In | Out | File |");
        let _ = writeln!(out, "| ---: | --- | --- | ---: | ---: | ---: | --- |");
        for (i, g) in ins.god_nodes.iter().enumerate() {
            let _ = writeln!(
                out,
                "| {} | `{}` | {} | {} | {} | {} | `{}` |",
                i + 1,
                g.name,
                g.kind,
                g.degree,
                g.in_degree,
                g.out_degree,
                g.file_path
            );
        }
        out.push('\n');
    }

    // Communities
    let _ = writeln!(out, "## Communities\n");
    let _ = writeln!(
        out,
        "Detected subsystems (Leiden community detection). Labels are inferred from the dominant module.\n"
    );
    if ins.communities.is_empty() {
        let _ = writeln!(out, "_None detected._\n");
    } else {
        let _ = writeln!(out, "| Community | Label | Size | Key nodes |");
        let _ = writeln!(out, "| ---: | --- | ---: | --- |");
        for c in &ins.communities {
            let key = if c.key_nodes.is_empty() {
                "—".to_string()
            } else {
                c.key_nodes
                    .iter()
                    .map(|n| format!("`{n}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let _ = writeln!(out, "| {} | {} | {} | {} |", c.community_id, c.label, c.size, key);
        }
        out.push('\n');
    }

    // Surprising connections
    let _ = writeln!(out, "## Surprising Connections\n");
    let _ = writeln!(
        out,
        "Edges that cross both a community and a module boundary — candidate coupling smells or key integration points.\n"
    );
    if ins.surprising_connections.is_empty() {
        let _ = writeln!(out, "_None detected._\n");
    } else {
        let _ = writeln!(out, "| Source | Target | Kind | Confidence | Modules |");
        let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
        for s in &ins.surprising_connections {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} | `{}` ⇄ `{}` |",
                s.source_name,
                s.target_name,
                s.kind,
                s.confidence,
                s.source_module,
                s.target_module
            );
        }
        out.push('\n');
    }

    // Dead code
    let _ = writeln!(out, "## Dead Code Candidates\n");
    let _ = writeln!(
        out,
        "Non-exported symbols with no inbound references. Verify before removing — dynamic dispatch and reflection are not tracked.\n"
    );
    if input.dead_code.is_empty() {
        let _ = writeln!(out, "_None detected._\n");
    } else {
        let _ = writeln!(out, "| Symbol | Kind | File |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for n in input.dead_code.iter().take(50) {
            let _ = writeln!(
                out,
                "| `{}` | {} | `{}:{}` |",
                n.name,
                n.kind.as_str(),
                n.file_path,
                n.start_line
            );
        }
        if input.dead_code.len() > 50 {
            let _ = writeln!(out, "\n_… and {} more._\n", input.dead_code.len() - 50);
        } else {
            out.push('\n');
        }
    }

    // Unresolved references
    let _ = writeln!(out, "## Unresolved References\n");
    if input.unresolved_total == 0 {
        let _ = writeln!(out, "_All references resolved._\n");
    } else {
        let _ = writeln!(
            out,
            "{} references could not be resolved. Most common:\n",
            input.unresolved_total
        );
        let _ = writeln!(out, "| Reference | Count |");
        let _ = writeln!(out, "| --- | ---: |");
        for (name, count) in input.unresolved_top.iter().take(20) {
            let _ = writeln!(out, "| `{}` | {} |", name, count);
        }
        out.push('\n');
    }

    // Suggested questions
    let _ = writeln!(out, "## Suggested Questions\n");
    for q in suggested_questions(ins) {
        let _ = writeln!(out, "- {q}");
    }
    out.push('\n');

    out
}

/// Templated exploration prompts seeded from the top god nodes and communities.
fn suggested_questions(ins: &GraphInsights) -> Vec<String> {
    let mut qs = Vec::new();
    if let Some(g) = ins.god_nodes.first() {
        qs.push(format!("How does `{}` connect to the rest of the system?", g.name));
    }
    if ins.god_nodes.len() > 1 {
        qs.push(format!(
            "What would break if I changed `{}`?",
            ins.god_nodes[1].name
        ));
    }
    if let (Some(a), Some(b)) = (ins.communities.first(), ins.communities.get(1)) {
        qs.push(format!(
            "How do the `{}` and `{}` subsystems interact?",
            a.label, b.label
        ));
    }
    if let Some(s) = ins.surprising_connections.first() {
        qs.push(format!(
            "Why does `{}` depend on `{}` across module boundaries?",
            s.source_name, s.target_name
        ));
    }
    if let Some(c) = ins.communities.first() {
        qs.push(format!("What is the responsibility of the `{}` community?", c.label));
    }
    if qs.is_empty() {
        qs.push("Run `ax index` first — the graph appears to be empty.".to_string());
    }
    qs
}

/// Summarize unresolved references into a total and top-N (name, count) list.
pub fn summarize_unresolved(names: &[String], top_n: usize) -> (usize, Vec<(String, usize)>) {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for n in names {
        *counts.entry(n.clone()).or_insert(0) += 1;
    }
    let mut ranked: Vec<(String, usize)> = counts.into_iter().collect();
    ranked.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    ranked.truncate(top_n);
    (names.len(), ranked)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ax_graph::{CommunitySummary, GodNode, SurprisingEdge};
    use ax_types::{Language, NodeKind};

    fn empty_insights() -> GraphInsights {
        GraphInsights {
            node_count: 0,
            edge_count: 0,
            num_communities: 0,
            modularity: 0.0,
            god_nodes: Vec::new(),
            communities: Vec::new(),
            surprising_connections: Vec::new(),
        }
    }

    fn dead_node(name: &str) -> Node {
        Node {
            id: format!("id-{name}"),
            kind: NodeKind::Function,
            name: name.to_string(),
            qualified_name: name.to_string(),
            file_path: "src/dead.rs".to_string(),
            language: Language::Rust,
            start_line: 3,
            end_line: 5,
            start_column: 0,
            end_column: 0,
            docstring: None,
            signature: None,
            visibility: None,
            is_exported: Some(false),
            is_async: None,
            is_static: None,
            is_abstract: None,
            decorators: None,
            type_parameters: None,
            return_type: None,
            updated_at: 0,
        }
    }

    #[test]
    fn report_contains_all_sections_and_data() {
        let insights = GraphInsights {
            node_count: 42,
            edge_count: 100,
            num_communities: 2,
            modularity: 0.51,
            god_nodes: vec![GodNode {
                node_id: "id-hub".to_string(),
                name: "hub".to_string(),
                qualified_name: "crate::hub".to_string(),
                file_path: "src/hub.rs".to_string(),
                kind: "function".to_string(),
                in_degree: 9,
                out_degree: 3,
                degree: 12,
            }],
            communities: vec![CommunitySummary {
                community_id: 0,
                label: "core".to_string(),
                size: 20,
                key_nodes: vec!["hub".to_string(), "router".to_string()],
            }],
            surprising_connections: vec![SurprisingEdge {
                source_id: "a".to_string(),
                target_id: "b".to_string(),
                source_name: "auth".to_string(),
                target_name: "render".to_string(),
                kind: "calls".to_string(),
                confidence: "inferred".to_string(),
                source_community: 0,
                target_community: 1,
                source_module: "auth".to_string(),
                target_module: "ui".to_string(),
                score: 0.9,
            }],
        };
        let dead = vec![dead_node("orphan")];
        let unresolved_top = vec![("mystery".to_string(), 4usize)];
        let input = ReportInput {
            project_name: "demo",
            insights: &insights,
            dead_code: &dead,
            unresolved_total: 7,
            unresolved_top: &unresolved_top,
        };

        let md = render_architecture_report(&input);

        assert!(md.contains("# Architecture Report: demo"));
        assert!(md.contains("## Overview"));
        assert!(md.contains("| Nodes | 42 |"));
        assert!(md.contains("## God Nodes"));
        assert!(md.contains("`hub`"));
        assert!(md.contains("## Communities"));
        assert!(md.contains("core"));
        assert!(md.contains("## Surprising Connections"));
        assert!(md.contains("`auth`"));
        assert!(md.contains("## Dead Code Candidates"));
        assert!(md.contains("`orphan`"));
        assert!(md.contains("## Unresolved References"));
        assert!(md.contains("`mystery`"));
        assert!(md.contains("## Suggested Questions"));
    }

    #[test]
    fn report_handles_empty_graph() {
        let insights = empty_insights();
        let input = ReportInput {
            project_name: "empty",
            insights: &insights,
            dead_code: &[],
            unresolved_total: 0,
            unresolved_top: &[],
        };

        let md = render_architecture_report(&input);

        assert!(md.contains("## God Nodes"));
        assert!(md.contains("_None detected._"));
        assert!(md.contains("_All references resolved._"));
        // With no data, the suggested-questions fallback kicks in.
        assert!(md.contains("Run `ax index` first"));
    }

    #[test]
    fn summarize_unresolved_ranks_by_frequency() {
        let names = vec![
            "foo".to_string(),
            "bar".to_string(),
            "foo".to_string(),
            "foo".to_string(),
            "bar".to_string(),
        ];
        let (total, top) = summarize_unresolved(&names, 10);
        assert_eq!(total, 5);
        assert_eq!(top[0], ("foo".to_string(), 3));
        assert_eq!(top[1], ("bar".to_string(), 2));
    }
}
