[package]
name = "ax-quality"
version = "2.0.14"
edition = "2021"

[dependencies]
ax-types = { workspace = true }
ax-utils = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
